/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ipgetterGUI;

import com.sun.glass.events.KeyEvent;
import java.awt.Color;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.StringSelection;
import java.awt.geom.RoundRectangle2D;
import java.net.*; // uses InetAddress and UnknownHostException

//@author Daxxtropezz
public class IPGetterGUI extends javax.swing.JFrame {

    String inputter;
    int xMouse;
    int yMouse;

    //Creates new form IPGetterGUI
    public IPGetterGUI() {
        initComponents();

        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 43, 43));
//        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("ip.png")).getImage());
    }

    void urlGetter() {
        try {

            inputter = linkAdd.getText();

            InetAddress address = InetAddress.getByName(inputter);
            ipAdd.setText(address.getHostAddress());

        } catch (UnknownHostException ex) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        title = new javax.swing.JLabel();
        ipAdd = new javax.swing.JTextField();
        linkAdd = new javax.swing.JTextField();
        copyTxt = new javax.swing.JButton();
        message = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("IP Getter");
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MainPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        title.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        title.setText("IP Getter");
        title.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                titleMouseDragged(evt);
            }
        });
        title.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                titleMousePressed(evt);
            }
        });
        MainPanel.add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 130));

        ipAdd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        ipAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ipAdd.setText("Internet Protocol Address");
        ipAdd.setEnabled(false);
        MainPanel.add(ipAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 440, 50));

        linkAdd.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        linkAdd.setForeground(new java.awt.Color(102, 102, 102));
        linkAdd.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        linkAdd.setText("Uniform Resource Locator");
        linkAdd.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                linkAddFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                linkAddFocusLost(evt);
            }
        });
        linkAdd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                linkAddKeyPressed(evt);
            }
        });
        MainPanel.add(linkAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 570, 50));

        copyTxt.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        copyTxt.setText("Copy");
        copyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyTxtActionPerformed(evt);
            }
        });
        MainPanel.add(copyTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 210, 110, 50));

        message.setForeground(new java.awt.Color(0, 102, 255));
        message.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        MainPanel.add(message, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 440, 20));

        getContentPane().add(MainPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void linkAddKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_linkAddKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_PERIOD) {
            linkAdd.setEnabled(false);
            linkAdd.setText(linkAdd.getText() + ".com");
            urlGetter();
            message.setText("click the copy button to enable the input field again!");
        }
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            urlGetter();
            message.setText("");
        }
    }//GEN-LAST:event_linkAddKeyPressed

    private void copyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyTxtActionPerformed
        StringSelection stringSelection = new StringSelection(ipAdd.getText());
        Clipboard clpbrd = Toolkit.getDefaultToolkit().getSystemClipboard();
        clpbrd.setContents(stringSelection, null);

        message.setText(inputter + "'s IP Address copied!");
        linkAdd.setEnabled(true);
        linkAdd.setText("Uniform Resource Locator");
        ipAdd.setText("Internet Protocol Address");
    }//GEN-LAST:event_copyTxtActionPerformed

    private void linkAddFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_linkAddFocusGained
        String placeholder = linkAdd.getText();
        linkAdd.setForeground(new Color(0, 0, 0));

        if (placeholder.trim().equals("Uniform Resource Locator")) {
            linkAdd.setText("www.");
        }
    }//GEN-LAST:event_linkAddFocusGained

    private void linkAddFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_linkAddFocusLost
        String placeholder = linkAdd.getText();
        linkAdd.setForeground(new Color(102, 102, 102));

        if (placeholder.trim().equals("") || placeholder.trim().equals("Uniform Resource Locator") || placeholder.trim().equals("www.")) {
            linkAdd.setText("Uniform Resource Locator");
        }
    }//GEN-LAST:event_linkAddFocusLost

    private void titleMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMousePressed
        xMouse = evt.getX();
        yMouse = evt.getY();
    }//GEN-LAST:event_titleMousePressed

    private void titleMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xMouse, y - yMouse);
    }//GEN-LAST:event_titleMouseDragged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IPGetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IPGetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IPGetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IPGetterGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new IPGetterGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton copyTxt;
    private javax.swing.JTextField ipAdd;
    private javax.swing.JTextField linkAdd;
    private javax.swing.JLabel message;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
